### ISSUE TITLE
Make it compatible with 6 LTS

### ISSUE THREAD

**Issue by phackwer** [cgauge/laravel-cognito-provider#4]
Hi,

In the company I work we always use Laravel LTS, which is currently 6. Because of this I had to fork your lib, adjust it to use v6, and rename the package to avoid any problems on composer. So, because I renamed it, the PR goes with the name I've put.

The changes I made were minimal and I didn't had issues to use the Token guard. We are using blackbits for all other operations, including login, I just needed the token part (they only made sesssion guard there).

So, the changes are this
![image](https://user-images.githubusercontent.com/4871786/112898012-36b37b80-90d8-11eb-86a4-11f85969961f.png)

If you want to make your package compatible with LTS 6, that's the only thing I had to do to get token working on 6.

Cheers

**Comment by deleugpn** [comment]
Hi @phackwer, sorry I did not get notified about your issue. Is this still the case to this day? 

Laravel 9 LTS is due to release very soon so I guess it's pointless now to add support for Laravel 6. Support for Laravel 9 has just been tagged.
