### ISSUE TITLE
Clarify last portion of readme.md

### ISSUE THREAD

**Issue by Taelkir** [cgauge/laravel-cognito-provider#5]
I can follow the readme instructions up until the 'UserFactory' section. Can it be clarified where the `final class CognitoUserFactory ...` portion of code is supposed to go, and how to register it in a ServiceProvider (i.e. do you create a new service provider with an artisan make command? What should it be called if you do this)? I felt like I was following the instructions clearly up to this point.

**Comment by abdala** [comment]
Hi, @Taelkir!

You can add the `CognitoUserFactory` wherever you prefer in your application and then register this class in any ServiceProvider also from your preference using:

```$this->app->bind(CustomerGauge\Cognito\Contracts\UserFactory, App\Auth\CognitoUserFactory::class);```

The `App\Auth` namespace is a suggestion here.

The main idea of having this class is to allow you to customize the creation of the User object with the parameter you need for your application.

Feel free to ask more if this is not clear enough.
